FROM node:20-alpine AS builder

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./
COPY tsconfig.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY src ./src

# Builder l'application
RUN npm run build

# Image finale
FROM node:20-alpine

WORKDIR /app

# Copier les dépendances et le build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./

EXPOSE 3001
#
CMD ["node", "dist/main.js"]
